name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag azure-table-storage-experiments:${{github.run_number}}
    - name: Push to docker hub
      run: docker push azure-table-storage-experiments:${{github.run_number}}
